name: ppd_python
channels:
   - conda-forge
dependencies:
   - python=3.7
   - ipython
   - jupyter
   - numpy
   - matplotlib
   - pandas
   - cartopy
   - xarray
   - netcdf4
   - seaborn
   - spyder
